function Products()
{
    return(
        <div className="products">            
            <span>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae dignissimos doloremque nisi itaque totam nihil neque voluptate, quidem deleniti ipsa fugit delectus provident ex maxime repellat animi veniam blanditiis assumenda? Sint aut cum at rerum saepe nobis quas quod autem voluptatem! Soluta quaerat asperiores laudantium sit tenetur maxime dolorum odit aperiam magnam est eaque, voluptate veritatis cumque doloremque velit reprehenderit quia provident perferendis voluptates! Aliquam minima cupiditate sed velit iure reiciendis ducimus, eligendi ipsam, et quod laborum ipsum obcaecati pariatur itaque! Quae cum molestias nihil et, magnam eaque iste consequatur dignissimos recusandae voluptatum corrupti similique at asperiores ipsa. Perspiciatis quas repellat doloremque cupiditate. Veniam id aut neque a amet molestiae quas aspernatur perspiciatis incidunt. Neque, eum eligendi! Architecto, laboriosam alias dolor necessitatibus illo ullam voluptas iste natus quia saepe fuga minima delectus asperiores tempore excepturi officiis magni culpa voluptate enim nihil magnam corporis accusamus? Et dolores temporibus saepe tempore nemo nesciunt ipsam obcaecati, nostrum fugit recusandae repudiandae adipisci incidunt illum iste. Quaerat excepturi provident architecto temporibus aspernatur quia dolores blanditiis ab illo laudantium nobis consequatur rerum libero soluta alias quibusdam dolorum quis, earum aperiam, at nemo harum cumque. Quae, magni ut saepe totam molestiae voluptas nam incidunt et eligendi commodi atque, at sint sed? Temporibus minus debitis veritatis eos excepturi a laboriosam perferendis id numquam accusantium, quasi libero voluptatum cumque deleniti harum distinctio dignissimos! Magni similique quos debitis doloribus necessitatibus? Beatae consequuntur debitis quod esse illum, quam iste totam alias culpa vitae iure perspiciatis facilis explicabo porro velit dolore repellat ipsam voluptatibus cumque! In corrupti praesentium blanditiis doloremque ipsum reprehenderit unde ratione commodi ducimus sequi. Atque, amet! Quisquam provident ducimus neque voluptas dolores commodi fugit? Modi sint nostrum perferendis totam reiciendis minima nesciunt aspernatur dicta voluptatum deleniti, veritatis ea cum amet porro excepturi. Quam exercitationem dolorum cum doloribus corrupti dolorem?
            </span>
        </div>
    )
}

export default Products;